//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pusher.PushNotifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pusher.PushNotifications.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.pushnotifications.pusher.com.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer_api/v1/instances/{0}/users/{1}.
        /// </summary>
        internal static string DeleteUserEndpoint {
            get {
                return ResourceManager.GetString("DeleteUserEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish method expects at least one interest.
        /// </summary>
        internal static string InvalidEmptyInterests {
            get {
                return ResourceManager.GetString("InvalidEmptyInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish method expects at least one user.
        /// </summary>
        internal static string InvalidEmptyUsers {
            get {
                return ResourceManager.GetString("InvalidEmptyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Id can&apos;t be an empty string.
        /// </summary>
        internal static string InvalidInstanceId {
            get {
                return ResourceManager.GetString("InvalidInstanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest {0} is too long (expected less than {1}, got {2}).
        /// </summary>
        internal static string InvalidInterest {
            get {
                return ResourceManager.GetString("InvalidInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish requests can only have up to {0} interests (given {1}).
        /// </summary>
        internal static string InvalidMaxInterests {
            get {
                return ResourceManager.GetString("InvalidMaxInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish requests can only have up to {0} users (given {1}).
        /// </summary>
        internal static string InvalidMaxUsers {
            get {
                return ResourceManager.GetString("InvalidMaxUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key can&apos;t be an empty string.
        /// </summary>
        internal static string InvalidSecretKey {
            get {
                return ResourceManager.GetString("InvalidSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id {0} is too long (expected less than {1}, got {2}).
        /// </summary>
        internal static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish_api/v1/instances/{0}/publishes/interests.
        /// </summary>
        internal static string PublishToInterestsEndpoint {
            get {
                return ResourceManager.GetString("PublishToInterestsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish_api/v1/instances/{0}/publishes/users.
        /// </summary>
        internal static string PublishToUsersEndpoint {
            get {
                return ResourceManager.GetString("PublishToUsersEndpoint", resourceCulture);
            }
        }
    }
}
