name: NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore 
    - name: Test
      env:
        PushNotificationsOptions__InstanceId: ${{ secrets.INSTANCE_ID }}
        PushNotificationsOptions__SecretKey: ${{ secrets.SECRET_KEY }}
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ./src/Pusher.PushNotifications/Pusher.PushNotifications.csproj -c Release -o ./package
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest          
    - name: Push
      run: dotnet nuget push ./package/Pusher.PushNotifications.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        
